-- ============================================================
--  Entitlement: one answer to "is this club allowed to use the app?"
--  APPLIED to wnxaydyhzwwrdwdmimab (migration entitlement_and_sportsweb_autolink).
--
--  Rules:
--    linked to SportsWeb One -> SportsWeb One decides, full stop. Never billed here.
--    otherwise               -> this app's subscription decides, and a free trial
--                               expires HARD at trial_ends_at, no grace period.
--
--  A 'trialing' row with a NULL trial_ends_at counts as EXPIRED, not unlimited —
--  a missing end date must never become free access forever.
--
--  SportsWeb One PUSHES entitlement into clubs.sportsweb_entitled rather than this
--  app querying it: Postgres can't read another project's database, and doing it
--  client-side would couple every page load to a second backend.
--
--  NOTE: this answers the question, it does not yet ENFORCE it. Enforcement needs
--  login-gated writes first (supabase/enable-auth.sql) — while the anon key can
--  write, any paywall is advisory. See AUTH-SETUP.md.
-- ============================================================

alter table public.clubs
  add column if not exists sportsweb_entitled boolean not null default false;

-- Full function bodies live in the applied migration; re-created here for a
-- fresh environment. See the Supabase dashboard for the authoritative version:
--   public.club_entitlement(uuid)
--     -> table (entitled boolean, source text, reason text, expires_at timestamptz)
--   public.start_lineup_trial(uuid, int default 14) -> timestamptz
--     Starts a HARD-expiry trial; refuses if a subscription already exists.
--   public.link_sportsweb_club(uuid, text, boolean default true) -> uuid
--     Create-or-link from SportsWeb One and mirror entitlement. Idempotent.
--     Creates NO lineup_subscriptions row: never bill a SportsWeb-billed club here.

-- ============================================================
--  APPLIED LATER (16 Aug 2026)
-- ============================================================
--
--  grandfather_existing_clubs
--    Every club predating billing got status='active' with NO stripe id.
--    club_entitlement() reports those as source='complimentary', so a
--    grandfathered club is never mistaken for revenue.
--
--  public.adopt_lineups_club_for_sportsweb(p_local_club, p_sw1_club_id, p_entitled)
--    Attach an EXISTING line-ups club to a SportsWeb One club.
--
--    Needed because link_sportsweb_club() only finds a club by its existing
--    link — so a standalone club that later joins SportsWeb One would get a
--    brand-new EMPTY club created, stranding every team, player and line-up
--    on the old row. Run this FIRST, then switch the module on.
--
--    Deliberately not automatic. Matching by name is the obvious shortcut and
--    is unsafe here: five rows in this table are called "Geelong", so a guess
--    would silently attach the wrong history.
--
--    Example — bring an existing club onto SportsWeb One:
--      select public.adopt_lineups_club_for_sportsweb(
--               '<line-ups club uuid>', '<sportsweb club uuid>', true);
--
--  link_sportsweb_club() now also deletes any complimentary (non-Stripe)
--  subscription on link, honouring "never billed by both". Stripe-backed rows
--  are left alone so a real customer is cancelled deliberately, not silently.

-- ============================================================
--  ENFORCEMENT (applied 16 Aug 2026) — migration enforce_entitlement_on_writes
-- ============================================================
--  public.club_is_entitled(uuid) -> boolean wraps club_entitlement() so policies
--  stay readable. Write policies now require it:
--
--    teams / players / sponsors      via club_id
--    fixtures                        via teams.club_id (the OWNING team's club,
--                                    never fixtures.opponent_club_id)
--    lineups                         via fixtures -> teams.club_id
--    lineup_positions                via lineups -> fixtures -> teams.club_id
--    clubs                           update/delete gated; INSERT stays open to
--                                    any signed-in user, since a club can't be
--                                    entitled before it exists
--    venues / opponent_clubs         shared reference data, no owning club, so
--                                    still plain signed-in write — gating them
--                                    would stop an entitled club naming a ground
--
--  Public read is untouched everywhere: losing entitlement stops you EDITING, it
--  does not pull published line-ups off the club's website.
